# run this using ansible
- hosts: localhost
  vars:
    home: "{{ ansible_env.HOME }}"
  tasks:

  - name: install packages
    yum: name={{ item }} state=present
    sudo: yes
    with_items:
    - emacs
    - git
    - tmux

  - name: install dotfiles
    copy: src={{ item }} dest={{ home }}/{{ item | basename }}
    with_fileglob:
    - home/.*

  - name: link bash profile
    lineinfile:
      dest: "{{ home }}/.bash_profile"
      line: "if test -f $HOME/.bash_profile_roaming; then source $HOME/.bash_profile_roaming; fi"

  - name: ensure bin dir
    file: dest={{ home }}/bin state=directory
    
  - name: install binfiles
    copy: src={{ item }} dest={{ home }}/bin/{{ item | basename }} mode=0755
    with_fileglob:
    - home/bin/*

  - name: ensure emacs dir
    file: dest={{ home }}/.emacs.d/rohan state=directory

  - name: install emacs files
    copy: src={{ item }} dest={{ home }}/.emacs.d/rohan/{{ item | basename }}
    with_fileglob:
    - home/emacs.d/rohan/*

  - name: link emacs
    lineinfile:
      create: yes
      dest: "{{ home }}/.emacs"
      line: "(load \"~/.emacs.d/rohan/init.el\")"
      insertbefore: BOF
