# run this using ansible
- hosts: localhost
  vars:
    home: "{{ ansible_env.HOME }}"
  tasks:

  - name: install packages
    yum: name={{ item }} state=present
    sudo: yes
    with_items:
    - emacs
    - git
    - keepassx
    - tmux

  - name: link dotfiles
    file: src={{ item }} dest={{ home }}/{{ item | basename }} state=link
    with_fileglob:
    - home/.*

  - name: link bash profile
    lineinfile:
      dest: "{{ home }}/.bash_profile"
      line: "if test -f $HOME/.bash_profile_roaming; then source $HOME/.bash_profile_roaming; fi"

  - name: ensure bin dir
    file: dest={{ home }}/bin state=directory
    
  - name: link bin files
    file: src={{ item }} dest={{ home }}/bin/{{ item | basename }} state=link
    with_fileglob:
    - home/bin/*

  - name: do lein init
    shell: lein --version
    async: 600
    poll: 0

  - name: ensure emacs dir
    file: dest={{ home }}/.emacs.d/rohan state=directory

  - name: link emacs files
    file: src={{ item }} dest={{ home }}/.emacs.d/rohan/{{ item | basename }} state=link
    with_fileglob:
    - home/emacs.d/rohan/*

  - name: ensure leindir
    file: dest={{ home }}/.lein state=directory

  - name: link lein files
    file: src={{ item }} dest={{ home }}/.lein/{{ item | basename }} state=link
    with_fileglob:
    - home/lein/*

  - name: link emacs
    lineinfile:
      create: yes
      dest: "{{ home }}/.emacs"
      line: "(load \"~/.emacs.d/rohan/init.el\")"
      insertbefore: BOF

  - name: do emacs init
    command: /usr/bin/emacs --batch \
      --eval "(setq rohan--init-packages t)" \
      --eval "(load \"/home/rohan/.emacs.d/rohan/init.el\")"
    async: 300
    poll: 0
