---
- name: link dotfiles
  file: src={{ item }} dest={{ devhome }}/{{ item | basename }} state=link
  with_fileglob:
  - home/.*

- name: link bash profile
  lineinfile:
    dest: "{{ devhome }}/.bash_profile"
    line: "if test -f $HOME/.bash_profile_roaming; then source $HOME/.bash_profile_roaming; fi"

- name: ensure bin dir
  file: dest={{ devhome }}/bin state=directory
    
- name: link bin files
  file: src={{ item }} dest={{ devhome }}/bin/{{ item | basename }} state=link
  with_fileglob:
  - home/bin/*
